Adds an integration test for Session persistence
mezzio/mezzio-session-cache pull request #26
Opened 2022-09-09 15:21 UTC by gsteel

|    Q          |   A
|-------------- | ------
| Documentation | yes
| QA            | yes

### Description

I was a bit surprised that a `Set-Cookie` header is sent for every request once a session has been established.

It makes sense that the session id is regenerated each time the session is changed, but cookies are also sent for each response when the session has not been altered.

This patch adds an integration test to document the behaviour of session-cache when used with `SessionMiddleware` and a PSR cache item pool. I used Symfony cache in dev because laminas-adapter-memory does not support a static TTL and I wanted to avoid mocks.

Is it expected behaviour to send a Set-Cookie header for every request once a session has been established?

2022-09-13 10:38 UTC, Ocramius requested changes

2022-09-13 10:38 UTC, Ocramius commented on composer.json
> +        "symfony/cache": "^5.4 || ^6.0",
IMO this part of the patch (which you explained in the PR description) is the only questionable bit. @boesing can you provide feedback on how we could do this with `laminas/laminas-cache` perhaps?

2022-09-14 11:32 UTC, boesing commented on composer.json
> +        "symfony/cache": "^5.4 || ^6.0",
Symfony provides PSR-6 via some `Array` cache (which is the equivalent of our `Memory` cache).
Since In-`Memory` cache is not persistent, the laminas `Memory` cache adapter does not provide support for PSR-6 and parts of PSR-16.

We can think about that and "fake" compatibility tho. Just needs to be implemented in the adapter tho.
Until then, we could use the `Apcu` adapter to provide proper PSR-6 support and to have integration tests here.

So we need `laminas-cache-storage-adapter-memory` + `laminas-cache` + `ext-apcu` (all added via `require-dev`):

```php

$adapter = new Apcu();
$cacheItemPool = new CacheItemPoolDecorator($adapter);
```

2022-09-14 11:58 UTC, gsteel commented on composer.json
> +        "symfony/cache": "^5.4 || ^6.0",
Thanks @boesing - I'll rebase with APCu once #30 is merged

2022-09-14 12:41 UTC, Ocramius commented on test/CacheSessionPersistenceIntegrationTest.php
> +    /** @var CacheItemPoolInterface */
I think we are on PHP 7.4 now, BTW 🤔

2022-09-14 12:42 UTC, Ocramius approved these changes
Merge when confident 👍

2022-09-14 12:57 UTC, merged

2022-09-14 12:58 UTC, Ocramius commented
Thanks @gsteel!