Add support for PHP 8.2, drop support for PHP 7.4
mezzio/mezzio-session-cache pull request #32
Opened 2022-10-14 15:37 UTC by gsteel

|    Q          |   A
|-------------- | ------
| New Feature   | yes

2022-10-14 15:39 UTC, gsteel commented
This isn't gonna happen until `apcu` is available for PHP 8.2

2022-10-14 15:42 UTC, Ocramius commented
Could we use a filesystem adapter?

2022-10-14 16:21 UTC, gsteel commented
> Could we use a filesystem adapter?

No, FS adapter doesn't support static TTL :( It has to either redis or apcu I believe

2022-10-14 16:23 UTC, Ocramius commented
Ah, that is unfortunate :| 

Redis will have the same issues then.

Can we somehow add static TTL support, perhaps?

2022-10-15 17:26 UTC, gsteel commented
Shouldn't be too long before it's available in apt: https://github.com/krakjoe/apcu/releases/tag/v5.1.22

2022-11-16 09:16 UTC, Ocramius commented
@gsteel with a rebase, this should be good to go, I think? :thinking: 

If not, we can install APCU manually, like we did in https://github.com/laminas/laminas-cache-storage-adapter-apcu/pull/45

2022-11-16 10:24 UTC, Ocramius requested changes

2022-11-16 10:24 UTC, Ocramius commented on .laminas-ci.json
> +        "8.2": true
This can now be dropped

2022-11-16 10:25 UTC, gsteel commented on .laminas-ci.json
> +        "8.2": true
Yes - I'll do that now 👍

2022-11-16 10:35 UTC, Ocramius approved these changes
Thanks @gsteel!

2022-11-16 10:35 UTC, merged